export const keys = {
  employees: (filters) => ["employees", filters],
  employee: (id) => ["employee", id],
  leave: (filters) => ["leave", filters],
  fees: (filters) => ["fees", filters],
  users: (filters) => ["users", filters],
  campus: () => ["lookup", "campus", {}],
  session: () => ["lookup", "session", {}],
  classes: (filters) => ["lookup", "class", filters],
  sections: (filters) => ["lookup", "section", filters],
  subjects: (filters) => ["lookup", "subject", filters],
  departments: () => ["lookup", "department", {}],
  designations: () => ["lookup", "designation", {}],
  dashboard: (filters) => ["dashboard", filters],
  resource: (id, filters) => ["resource", id, filters],
  lookup: (name, filters = {}) => ["lookup", name, filters],
};
