import {
  LayoutDashboard,
  GraduationCap,
  Users,
  Wallet,
  Landmark,
  ShoppingCart,
  Package,
  Building2,
  Shield,
  ClipboardList,
  CalendarDays,
  BookOpen,
  Layers,
  CalendarRange,
  CalendarClock,
  FileCheck,
  ClipboardCheck,
  UserPlus,
  UserRoundSearch,
  BookMarked,
  FileOutput,
  IdCard,
  BadgeCheck,
  CalendarOff,
  UserCheck,
  UserMinus,
  Receipt,
  TrendingUp,
  FolderTree,
  DoorOpen,
  Mail,
  School,
  KeyRound,
} from "lucide-react";

export const NAV = [
  {
    title: "Overview",
    items: [
      { to: "/dashboard", label: "Dashboard", icon: LayoutDashboard },
    ],
  },
  {
    title: "Academic",
    items: [
      { to: "/academic/classes", label: "Classes", icon: GraduationCap },
      { to: "/academic/sections", label: "Sections", icon: Layers },
      { to: "/academic/subjects", label: "Subjects", icon: BookOpen },
      { to: "/academic/sessions", label: "Sessions", icon: CalendarRange },
      { to: "/academic/routines", label: "Routines", icon: CalendarClock },
      { to: "/academic/homework", label: "Homework", icon: ClipboardList },
      { to: "/academic/exams", label: "Exams", icon: FileCheck },
      { to: "/academic/attendance", label: "Attendance", icon: ClipboardCheck },
    ],
  },
  {
    title: "Students",
    items: [
      { to: "/stad/students", label: "Students", icon: Users },
      { to: "/stad/admission", label: "Admission", icon: UserPlus },
      { to: "/stad/applicants", label: "Applicants", icon: UserRoundSearch },
      { to: "/stad/hifz", label: "Hifz", icon: BookMarked },
      { to: "/stad/tc", label: "Transfer certificates", icon: FileOutput },
    ],
  },
  {
    title: "Staff / HR",
    items: [
      { to: "/hris/employees", label: "Employees", icon: IdCard },
      { to: "/hris/departments", label: "Departments", icon: Building2 },
      { to: "/hris/designations", label: "Designations", icon: BadgeCheck },
      { to: "/hr/leave", label: "Leave", icon: CalendarOff },
      { to: "/hr/recruitment", label: "Recruitment", icon: UserCheck },
      { to: "/hr/resignation", label: "Resignation", icon: UserMinus },
    ],
  },
  {
    title: "Finance",
    items: [
      { to: "/fees/collection", label: "Fee collection", icon: Wallet },
      { to: "/fees/types", label: "Fee types", icon: Receipt },
      { to: "/account/payments", label: "Payments", icon: Landmark },
      { to: "/account/income", label: "Income", icon: TrendingUp },
      { to: "/account/heads", label: "Account heads", icon: FolderTree },
    ],
  },
  {
    title: "Operations",
    items: [
      { to: "/procurement/requisitions", label: "Requisitions", icon: ShoppingCart },
      { to: "/store/products", label: "Inventory", icon: Package },
      { to: "/front-office/visitors", label: "Visitors", icon: DoorOpen },
      { to: "/front-office/postal", label: "Postal", icon: Mail },
      { to: "/admin/events", label: "Events", icon: CalendarDays },
    ],
  },
  {
    title: "System",
    items: [
      { to: "/settings/campus", label: "Campuses", icon: School },
      { to: "/settings/users", label: "Users", icon: Shield },
      { to: "/settings/roles", label: "Roles", icon: KeyRound },
    ],
  },
];
